//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioPractico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Prospecto
    {
        public int pros_id { get; set; }
        [DisplayName("Nombre")]
        [Required(ErrorMessage = "Campo Obligatorio")]
        [RegularExpression(@"^[A-ZÁÉÍÓÚñáéíóúÑ]+([a-zA-ZÁÉÍÓÚñáéíóúÑ.,]*[\D\s]*)*$", ErrorMessage = "Debe iniciar con mayuscula")]
        public string pros_nombre { get; set; }
        [DisplayName("Primer Apellido")]
        [RegularExpression(@"^[A-ZÁÉÍÓÚñáéíóúÑ]+([a-zA-ZÁÉÍÓÚñáéíóúÑ.,]*[\s]*)*$", ErrorMessage = "Debe iniciar con mayuscula")]
        public string pros_apellidoP { get; set; }
        [DisplayName("Segundo Apellido")]
        [RegularExpression(@"^[A-ZÁÉÍÓÚñáéíóúÑ]+([a-zA-ZÁÉÍÓÚñáéíóúÑ.,]*[\s]*)*$", ErrorMessage = "Debe iniciar con mayuscula")]
        public string pros_apellidoM { get; set; }

        [DisplayName("Calle")]
        [RegularExpression(@"^[A-ZÁÉÍÓÚñáéíóúÑ]+([a-zA-ZÁÉÍÓÚñáéíóúÑ.,]*[\s]*)*$", ErrorMessage = "Debe iniciar con mayuscula")]
        public string pros_calle { get; set; }

        [DisplayName("Número")]
        [RegularExpression(@"^\d{1,5}$", ErrorMessage = "Uno a cinco dígitos")]
        public string pros_num { get; set; }
        [DisplayName("Colonia")]
        [RegularExpression(@"^[A-ZÁÉÍÓÚñáéíóúÑ]+([a-zA-ZÁÉÍÓÚñáéíóúÑ.,]*[\s]*)*$", ErrorMessage = "Debe iniciar con mayuscula")]
        public string pros_colonia { get; set; }
        [DisplayName("Código Postal")]
        [RegularExpression(@"^\d{5}$", ErrorMessage = "Cinco dígitos")]
        public string pros_cp { get; set; }
        [DisplayName("Teléfono")]
        [RegularExpression(@"^\d{10,15}$", ErrorMessage = "Diez dígitos")]
        public string pros_tel { get; set; }
        [DisplayName("RFC")]
        [RegularExpression(@"^([A-ZÑ&]{3,4}) ?(?:- ?)?(\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])) ?(?:- ?)?([A-Z\d]{2})([A\d])$", ErrorMessage = "Ingrese un RFC Válido")]
        public string pros_rfc { get; set; }
        [DisplayName("Estatus")]
        public string pros_estatus { get; set; }
        [DisplayName("Notas")]
        public string pros_notas { get; set; }
        public string pros_rutas { get; set; }
    }
}
